#############################################################################################################

name: ecommerce_shopping_project
description: "Complete ECommerce Shopping App Project with Flutter, Firebase Auth, Cloud Firestore, Firebase Storage and Hive"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0

#############################################################################################################

  flutter_riverpod: ^2.5.1                # State Management Solution
  get_it: ^7.7.0                          # Dependency Injection Service
  flutter_screenutil: ^5.9.3              # Responsive & Adaptive Design
  go_router: ^14.2.2                      # Advanced Navigation & Routing System

  firebase_core: ^3.3.0                   # Firebase Services
  firebase_auth: ^5.1.4                   # Firebase Authentication Service

  card_swiper: ^3.0.1                     # Carousel Image Slider
  smooth_page_indicator: ^1.2.0           # Image Slider Pagination
  flutter_slidable: ^3.1.1                # Advanced Version of Flutter Dismissible Widget
  flutter_animate: ^4.5.0                 # Advanced Animations
  flutter_custom_carousel: ^0.1.0+1       # Advanced Built-In Slider Animations with flutter_animate package
  zoom_pinch_overlay: ^1.4.3              # Advanced Version of Flutter Interactive Widget
  easy_stepper: ^0.8.5                    # Payment Screen Horizontal Top Stepper Widget
  flutter_credit_card: ^4.0.1             # Credit Card Validation
  shimmer: ^3.0.0                         # Animated Product Card Placeholders while Loading State
  loading_animation_widget: ^1.2.1        # Animated Loading Progress Indicators 
  flutter_rating_bar: ^4.0.1              # Product Rating Bar
  msh_checkbox: ^2.0.1                    # Animated Checkbox Widget
  flutter_any_logo: ^1.1.1                # Brand Logos
  cupertino_icons: ^1.0.6                 # UI Icons
  flutter_tabler_icons: ^1.35.0           # UI Icons
  unicons: ^2.1.2                         # UI Icons


#############################################################################################################

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

#############################################################################################################

  assets:
    - assets/images/
    - assets/images/digital_wallet/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
 
######################################################################################