import 'package:ecommerce_shopping_project/models/product.dart';

import 'package:ecommerce_shopping_project/utilities/utilities_library_imports.dart';

List<Product> dummyAllProducts = [
  Product(
    id: '000001',
    title: 'High Neck Shoulder T-Shirt',
    brand: 'Louis Vuitton',
    summary: 'Sleeveless T-shirt',
    detailedDescription:
        'This sleeveless T-shirt is cut from soft, lightweight cotton jersey for elevated everyday styling. The classic straight-cut shape is refreshed with a casual high neckline and the runway’s directional broad shoulders for a defined silhouette. A metallic LV circle chain adds a modern signature accent to the chest.',
    price: 199.99,
    mainPhoto: AppImages.productImage12,
    photos: [
      AppImages.productImage1,
      AppImages.productImage2,
      AppImages.productImage3,
      AppImages.productImage4,
    ],
    collections: [],
    isOnSale: true,
    saleLastDate: '19.03.2024',
    salePrice: 179.99,
    createdAt: '12.03.2024',
    colors: [
      'FF0000',
      '05FF00',
      '0075FF',
      'FF00B8',
      'A0207C',
    ],
    sizes: [
      'XS',
      'S',
      'M',
      'L',
      'XL',
    ],
    totalOrdersCount: 32,
    totalLikesCount: 152,
    totalRating: 3.45,
    // storeId: dummyStores[0].id,
    // storeName: dummyStores[0].name,
    storeId: 'dummyStores[0].id',
    storeName: 'dummyStores[0].name',
    stockCount: 432,
    shippingFee: 0,
    estimatedShippingDurationInDays: 3,
    reviews: [],
  ),
  Product(
    id: '000002',
    title: 'Buttoned Boot-Cut Jeans',
    brand: 'Zara',
    summary: 'For a retro take, team with a floral shirt',
    detailedDescription:
        'Bootcut jeans are an endearingly flattering cut and our collection has contemporary designs to suit every silhouette. Low-rise, mid-rise and high-rise styles are - like our wider collection which features skinny, flared and baggy jeans - made from comfortable denim',
    price: 86.99,
    mainPhoto: AppImages.productImage11,
    photos: [
      AppImages.productImage6,
      AppImages.productImage7,
      AppImages.productImage8,
      AppImages.productImage9,
    ],
    createdAt: '19.02.2024',
    colors: [
      '312525',
      'F9AC15',
      '657310',
      '104973',
      'FFD8D3',
      '5D006D',
    ],
    sizes: [
      '08',
      '11',
      '14',
    ],
    totalOrdersCount: 11,
    totalLikesCount: 9,
    totalRating: 1.56,
    storeId: 'dummyStores[0].id',
    storeName: 'dummyStores[0].name',
    stockCount: 12,
    shippingFee: 0,
    estimatedShippingDurationInDays: 7,
    collections: [],
    reviews: [],
  ),
  Product(
    id: '000003',
    title: 'Gucci Pantcaon22',
    brand: 'Gucci',
    summary: 'For a retro take, team with a floral shirt',
    detailedDescription:
        'Bootcut jeans are an endearingly flattering cut and our collection has contemporary designs to suit every silhouette. Low-rise, mid-rise and high-rise styles are - like our wider collection which features skinny, flared and baggy jeans - made from comfortable denim',
    price: 86.99,
    mainPhoto: AppImages.productImage10,
    photos: [
      AppImages.productImage6,
      AppImages.productImage7,
      AppImages.productImage8,
      AppImages.productImage9,
    ],
    createdAt: '19.02.2024',
    colors: [
      '312525',
      'F9AC15',
      '657310',
      '104973',
      'FFD8D3',
      '5D006D',
    ],
    sizes: [
      '08',
      '11',
      '14',
    ],
    totalOrdersCount: 11,
    totalLikesCount: 9,
    totalRating: 1.56,
    storeId: 'dummyStores[0].id',
    storeName: 'dummyStores[0].name',
    stockCount: 12,
    shippingFee: 4.99,
    estimatedShippingDurationInDays: 7,
    collections: [],
    reviews: [],
  ),
  Product(
    id: '000004',
    title: 'Channel Crop',
    brand: 'Louis Vuitton',
    summary: 'Sleeveless T-shirt',
    detailedDescription:
        'This sleeveless T-shirt is cut from soft, lightweight cotton jersey for elevated everyday styling. The classic straight-cut shape is refreshed with a casual high neckline and the runway’s directional broad shoulders for a defined silhouette. A metallic LV circle chain adds a modern signature accent to the chest.',
    price: 709.99,
    mainPhoto: AppImages.productImage8,
    photos: [
      AppImages.productImage1,
      AppImages.productImage2,
      AppImages.productImage3,
      AppImages.productImage4,
    ],
    createdAt: '12.03.2024',
    colors: [
      'FF0000',
      '05FF00',
      '0075FF',
      'FF00B8',
      'A0207C',
    ],
    sizes: [
      'XS',
    ],
    totalOrdersCount: 32,
    totalLikesCount: 152,
    totalRating: 3.45,
    // storeId: dummyStores[0].id,
    // storeName: dummyStores[0].name,
    storeId: 'dummyStores[0].id',
    storeName: 'dummyStores[0].name',
    stockCount: 432,
    shippingFee: 0,
    estimatedShippingDurationInDays: 3,
    collections: [],
    reviews: [],
  ),
  Product(
    id: '000005',
    title: 'Louis Vuitton Jacket',
    brand: 'Louis Vuitton',
    summary: 'Sleeveless T-shirt',
    detailedDescription:
        'This sleeveless T-shirt is cut from soft, lightweight cotton jersey for elevated everyday styling. The classic straight-cut shape is refreshed with a casual high neckline and the runway’s directional broad shoulders for a defined silhouette. A metallic LV circle chain adds a modern signature accent to the chest.',
    price: 998.00,
    mainPhoto: AppImages.productImage3,
    photos: [
      AppImages.productImage1,
      AppImages.productImage2,
      AppImages.productImage3,
      AppImages.productImage4,
    ],
    createdAt: '12.03.2024',
    colors: [
      'FF0000',
      '05FF00',
      '0075FF',
      'FF00B8',
      'A0207C',
    ],
    sizes: [
      'M',
      'L',
    ],
    totalOrdersCount: 32,
    totalLikesCount: 152,
    totalRating: 3.49,
    // storeId: dummyStores[0].id,
    // storeName: dummyStores[0].name,
    storeId: 'dummyStores[0].id',
    storeName: 'dummyStores[0].name',
    stockCount: 432,
    shippingFee: 1.99,
    estimatedShippingDurationInDays: 3,
    collections: [],
    reviews: [],
  ),
  Product(
    id: '000006',
    title: 'Giorgino Armani Coat',
    brand: 'Louis Vuitton',
    summary: 'Sleeveless T-shirt',
    detailedDescription:
        'This sleeveless T-shirt is cut from soft, lightweight cotton jersey for elevated everyday styling. The classic straight-cut shape is refreshed with a casual high neckline and the runway’s directional broad shoulders for a defined silhouette. A metallic LV circle chain adds a modern signature accent to the chest.',
    price: 199.99,
    mainPhoto: AppImages.productImage4,
    photos: [
      AppImages.productImage1,
      AppImages.productImage2,
      AppImages.productImage3,
      AppImages.productImage4,
    ],
    createdAt: '12.03.2024',
    colors: [
      'FF0000',
      '05FF00',
      '0075FF',
      'FF00B8',
      'A0207C',
    ],
    sizes: [
      'XL',
    ],
    totalOrdersCount: 32,
    totalLikesCount: 152,
    totalRating: 3.45,
    // storeId: dummyStores[0].id,
    // storeName: dummyStores[0].name,
    storeId: 'dummyStores[0].id',
    storeName: 'dummyStores[0].name',
    stockCount: 432,
    shippingFee: 0,
    estimatedShippingDurationInDays: 3,
    collections: [],
    reviews: [],
  ),
];
