import 'package:ecommerce_shopping_project/models/dummy_data/dummy_collections.dart';
import 'package:ecommerce_shopping_project/models/product.dart';
import 'package:ecommerce_shopping_project/utilities/utilities_library_imports.dart';

var dummyProductShortList = [
  Product(
    title: 'Edition Valencia Linen Shirt',
    price: 69.992342345231115111452345234535234523345234,
    mainPhoto: AppImages.productImage12,
    brand: 'Ver',
    categories: [
      // dummyCategories[0],
    ],
    collections: [
      // dummyCollections[0],
      dummyCollection1,
    ],
    colors: [],
    createdAt: '123',
    description: 'sdfgsdf',
    estimatedShippingDurationInDays: 2,
    id: '234',
    isFreeShipping: true,
    photos: [],
    reviews: [],
    shippingPrice: 0,
    sizes: [],
    stockCount: 12,
    storeId: '01',
    storeName: 'sdfg',
    summary: 'asasdfasd',
    totalLikesCount: 12,
    totalOrdersCount: 32,
    totalRating: 2.2,
  ),
  Product(
    title:
        'CroppedCroppedCroppedCroppedCroppedCroppedCroppedCroppedCropped Stock-Fit',
    price: 69.992342345231115111452345234535234523345234,
    mainPhoto: AppImages.productImage11,
    brand: 'Ver',
    categories: [],
    colors: [],
    createdAt: '123',
    description: 'sdfgsdf',
    estimatedShippingDurationInDays: 2,
    id: '234',
    isFreeShipping: true,
    photos: [],
    reviews: [],
    shippingPrice: 0,
    sizes: [],
    stockCount: 12,
    storeId: '01',
    storeName: 'sdfg',
    summary: 'asasdfasd',
    totalLikesCount: 12,
    totalOrdersCount: 32,
    totalRating: 2.2,
    collections: [],
  ),
  Product(
    title: 'Nike AirMax XXXL-CRX',
    price: 69.992342345231115111452345234535234523345234,
    mainPhoto: AppImages.productImage10,
    brand: 'Ver',
    categories: [],
    colors: [],
    createdAt: '123',
    description: 'sdfgsdf',
    estimatedShippingDurationInDays: 2,
    id: '234',
    isFreeShipping: true,
    photos: [],
    reviews: [],
    shippingPrice: 0,
    sizes: [],
    stockCount: 12,
    storeId: '01',
    storeName: 'sdfg',
    summary: 'asasdfasd',
    totalLikesCount: 12,
    totalOrdersCount: 32,
    totalRating: 2.2,
    collections: [],
  ),
  Product(
    title: 'Gucci Pantcaon',
    price: 69.992342345231115111452345234535234523345234,
    mainPhoto: AppImages.productImage8,
    brand: 'Ver',
    categories: [],
    colors: [],
    createdAt: '123',
    description: 'sdfgsdf',
    estimatedShippingDurationInDays: 2,
    id: '234',
    isFreeShipping: true,
    photos: [],
    reviews: [],
    shippingPrice: 0,
    sizes: [],
    stockCount: 12,
    storeId: '01',
    storeName: 'sdfg',
    summary: 'asasdfasd',
    totalLikesCount: 12,
    totalOrdersCount: 32,
    totalRating: 2.2,
    collections: [],
  ),
];
